export {default as Navbar} from "./navbar/Navbar"
export {default as About} from "./about/About" 
export {default as Home} from "./home/Home"
export {default as Projects} from "./projects/Projects"
export {default as Contact} from "./contact/Contact"
export {default as Alert} from "./alert/Alert"
export {default as Footer} from "./footer/Footer"